version: '3'

services:
  db:
    image: postgres:13
    container_name: booking_db
    ports:
      - 5438:5432
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    image: booking/web:latest
    container_name: booking_web
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    environment:
      CREATE_DB_ON_INIT: 'true'
